server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Esto asegura que si el usuario recarga una ruta (ej. /chat), 
        # Nginx devuelva index.html en lugar de un error 404.
        try_files $uri $uri/ /index.html;
    }

    # Redirigir errores del servidor a la página estática /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
